API_HOST_URL: 'https://courses.techdiplomacyacademy.org'
ENVIRONMENT_DISPLAY_NAME: 'Live'
FEEDBACK_EMAIL_ADDRESS: 'support@techdiplomacyacademy.org'
OAUTH_CLIENT_ID: 'xArIcasO3dV3Nlk3qjHIDv7JFPxac8dPRSathUXj'
TOKEN_TYPE: 'BEARER'
WEB_LOGIN: true

UI_COMPONENTS:
    COURSE_BANNER_ENABLED: true
    COURSE_TOP_TAB_BAR_ENABLED: false
    COURSE_UNIT_PROGRESS_ENABLED: false
    COURSE_NESTED_LIST_ENABLED: false
